### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-Hybrid-identity#10]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Update diagrams to use new Azure icons
- Re-screenshot the entire lab (much of them are out of date)
- Add in Cloud Provisioning
- Update AAD App Proxy to use myapplications.microsoft.com instead of "myapps"

**Comment by DawnmarieDesJardins** [comment]
Add to update - Review and address issue #8

**Comment by JoshuaL1** [comment]
Further Suggestions:
1. Incorporate the new unified SSPR sign-up experience -https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-registration-mfa-sspr-combined

2. Update screenshots/experience around "Workspaces" - https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/access-panel-collections

**Comment by rdendtler** [comment]
I'm good with suggestions above.

**Comment by DawnmarieDesJardins** [comment]
This June 2020 update has been moved to a June test/fix.  Closing update issue.
