### ISSUE TITLE
Review - Task 8: Test an Azure AD Application Proxy application

### ISSUE THREAD

**Issue by YRollHid** [microsoft/MCW-Hybrid-identity#11]
Hello,

please review this step because it didn't works for me.
The only way is to resend invitation and use the link as you can see [here](https://drive.google.com/file/d/17KSmxFjm4rVmAYc2ymdN66J6ZbF5YxCa/view?usp=sharing).

After you has accepted the invitation you can switch organization inside https://myapps.microsoft.com

Regards,
Yans

**Comment by paulopsgility** [comment]
@YRollHid Thanks for the feedback. We are in the middle of test/fix so we will take a look at it and verify/fix.

**Comment by paulopsgility** [comment]
Closing, resolved in next test/fix
