### ISSUE TITLE
Add notes to whiteboard slides

### ISSUE THREAD

**Issue by DeanGross** [microsoft/MCW-Hybrid-identity#13]
It would be great if the whiteboard slides had speaker notes, reference information on them. For example, slide 14 has a decision tree, and asks a question about signins natively supported by Azure AD. Not everyone knows what is natively supported, so we will have to go do some research when the client asks this question. Including the supporting information on this slide and others would be very helpful

**Comment by paulopsgility** [comment]
@DeanGross The student and trainer guides contain the details of the scenario and the solution. These contain both detailed explanations and links to supporting documentation. The slides are not standalone. You might sometimes see detailed notes in slides of an MCW but these are usually just copied directly from those other docs. If you study and understand those docs you should be prepared to delivery the deck.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete.
