### ISSUE TITLE
Whiteboard - slide 45

### ISSUE THREAD

**Issue by DeanGross** [microsoft/MCW-Hybrid-identity#14]
how do we ensure that the staging AAD connect server has the same configuration settings as the production server?

**Comment by paulopsgility** [comment]
@DeanGross Issues reported via GitHub are intended to help identify and mitigate issues with the content itself, not to provide support of the underlying technology. 

Let me know if I am misunderstanding your question.

**Comment by DeanGross** [comment]
Sorry, i was not very clear. I was thinking that since we are trying to educate people, that it would be helpful if the slide included some speaker notes that the teacher could use to explain to the students how to ensure that they did not swap to a standby machine that had a different configuration which would cause unexpected problems,

**Comment by DawnmarieDesJardins** [comment]
Thanks @DeanGross 
I'm going to mark this issue as an enhancement for review/consideration in the next update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #25
