### ISSUE TITLE
Whiteboard-slide 48

### ISSUE THREAD

**Issue by DeanGross** [microsoft/MCW-Hybrid-identity#15]
what is meant by the statement "different versions of the Microsoft Azure AD Connect Agent Updater service"? how is this relevant to the app proxy service?

**Comment by paulopsgility** [comment]
@DeanGross Issues reported via GitHub are intended to help identify and mitigate issues with the content itself, not to provide support of the underlying technology. Please see the trainer guide for details of the solution, I believe your particular question is answered there.

Let me know if I am misunderstanding your question.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with above clarification.
