### ISSUE TITLE
Please state prerequisites at the beginning of each  lab guides.

### ISSUE THREAD

**Issue by anjaneshbabu** [microsoft/MCW-Hybrid-identity#17]
It would be ideal to mention pre-requisites within  the step-by-step  - ideally at the beginning.

For example the lab exercises 

[HOL step-by step - Hybrid identity.html
](https://cloudworkshop.blob.core.windows.net/hybrid-identity/Hands-on%20lab/HOL%20step-by%20step%20-%20Hybrid%20identity.html
)

Should mention that the  steps below are to be completed _before_ commencing the lab.

[Before the hands-on lab - Hybrid identity.html ](https://cloudworkshop.blob.core.windows.net/hybrid-identity/Hands-on%20lab/Before%20the%20hands-on%20lab%20-%20Hybrid%20identity.html)

Thank you

**Comment by DawnmarieDesJardins** [comment]
@anjaneshbabu 
Thanks Anajanesh.  We have an approved template that we work from but I am going to label this issue as an enhancement for discussion with our leads at the next update.  We appreciate your suggestion!

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #25.  Workshop following management approved templates.
