### ISSUE TITLE
Can not complete task 6 in before HOL

### ISSUE THREAD

**Issue by nhutpm219** [microsoft/MCW-Hybrid-identity#18]
Hi, as mentioned in title, I can not find the CreateDemoUsers.ps1 and CreateDemoUsers.csv because when I click to https://gallery.technet.microsoft.com/scriptcenter/Create-UsersGroup-for-9ee1de26 it will point to https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=TechNet-Gallery and I can find them there.

**Comment by DawnmarieDesJardins** [comment]
@nhutpm219 
Thank you for bringing this to our attention.  We are currently working on a review of this workshop and should have an updated version for you next week.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #20
