### ISSUE TITLE
More specific links

### ISSUE THREAD

**Issue by mzbowe** [microsoft/MCW-Hybrid-identity#2]
On the before document when i went there, its a cornucopia.  Even though title mentioned, why not link directly to the docs.  Also, the link took my out of the doc, versus opening a new tab.  Maybe the produced version will fix that?

here
Review online documentation regarding Azure Active Directory at https://docs.microsoft.com/en-us/azure/active-directory/ focusing in particular on its integration with Active Directory and its B2B capabilities.

**Comment by polichtm** [comment]
Hi Mark,
It's not clear to me what you mean by this comment. Which document are you referring to and which specific section in that document? Your statement seems to imply that this is the Before the hands-on lab guide, which is not intended to provide links to any documentation, but simply guide through steps necessary to prepare the lab for students
Pls clarify
rgds
Marcin

**Comment by DawnmarieDesJardins** [comment]
Closing issue with publishing workshop
