### ISSUE TITLE
2021 Q4 updates

### ISSUE THREAD

**Issue by dwnatwick** [microsoft/MCW-Hybrid-identity#24]
**HOL**  

- Align with WDS solution – verify that all requirements and objectives in WDS are also covered in HOL 
- Explore password-less options with Windows Hello for Business and Windows Authenticator app 
- Add resiliency: Fail-over domain and pass-through agents 

**WDS** 

- More discussion around Password-less authentication options 
- Issue #16 – point out the licensing requirements for Intune and why E5 may be needed 
- Issue #14 – more notes/discussion/reference in the WDS student guide on resiliency with Azure AD Connect

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #25
