### ISSUE TITLE
Lab Guide Updates

### ISSUE THREAD

**Issue by Kalyani7744** [microsoft/MCW-Hybrid-identity#27]
1. [Exercise 1, Task6 Step 2](https://github.com/microsoft/MCW-Hybrid-identity/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Hybrid%20identity.md#task-6-install-azure-ad-connect) For Installing Azure AD Connect, it is mentioned to **login to Azure Portal in Internet Explorer** inside DC1 Virtual Machine. But Internet Explorer 11 does not support Azure portal and getting an error message as below.

There are few more instructions that suggest to login to azure portal from Internet Explorer inside DC1 Virtual Machine which has to be changed.

![IE1](https://user-images.githubusercontent.com/83349665/126175068-ef88a7ff-6f37-43e6-aa5b-0c38e6ca1f2d.PNG)

2. [Exercise 4, Task 4 step 1](https://github.com/microsoft/MCW-Hybrid-identity/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Hybrid%20identity.md#task-4-install-pass-through-agent) For **Installing pass through agent** inside BDC-1 Virtual Machine, it is mentioned to open Azure Portal inside Internet Explorer and getting same error message as shown above.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #28
