### ISSUE TITLE
Workshop abstract is taken from a different workshop and has nothing to do with the Hybrid Identity

### ISSUE THREAD

**Issue by Kirbogd** [microsoft/MCW-Hybrid-identity#29]
https://github.com/microsoft/MCW-Hybrid-identity#workshop
_In this workshop, you will learn to setup and configure a hybrid identity solution that integrates an existing on-premises identity solution with Azure. You will learn how to secure the virtual network by deploying a network virtual appliance and configure firewall rules and route tables. Additionally, you will set up access to the virtual network with a jump box and a site-to-site VPN connection.

At the end of the workshop, you will be better able to plan and design virtual networks in Azure with multiple subnets to filter and control network traffic. In addition, you will learn to create a virtual network and provision subnets, create route tables with required routes, build a management jump box, configure firewalls to control traffic flow, and configure site-to-site connectivity._
Feels like it belongs to some other workshop

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #30
