### ISSUE TITLE
Before Hands-on-lab:Task 6: Script is not working

### ISSUE THREAD

**Issue by SMSeerat** [microsoft/MCW-Hybrid-identity#35]
[Task 6:](https://github.com/microsoft/MCW-Hybrid-identity/blob/main/Hands-on%20lab/Before%20the%20hands-on%20lab%20-%20Hybrid%20identity.md#task-6-configure-contosolocal-active-directory) The script to modify settings of the AD user accounts in Step 9 is not fetching user AGAyers.

**Comment by DawnmarieDesJardins** [comment]
@KitSkin @texnomore 
Hello.  Any update for us?

**Comment by dom49in** [comment]
In your script where ever you see DC=contoso, DC=local, replace it with DC=corp, DC=contoso, DC=com

Note: In Task#3 step#3, it states Domain Name: corp.contoso.com.

For the remainder of the lab do the same.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #36
