### ISSUE TITLE
The lab content appears to have been updated; please update the content.

### ISSUE THREAD

**Issue by yashmadan123** [microsoft/MCW-Hybrid-identity#40]
The lab content appears to have been updated; please update the content.

**Comment by DawnmarieDesJardins** [comment]
Thank you for your input. We will update content as soon as we are able.

**Comment by sumitmalik51** [comment]
Hi @dawnmarrie, The lab content needs refreshment as almost all the steps and screenshots are out of date and some of the steps are depreciated already, with the current lab guide there will be a lot of issues due to the content. 

Thanks

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 - Thanks Sumit.  As is, is the lab broken?

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 - Thanks Sumit - we're getting an author linked up to do a test/fix and update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR#41 - Lab has been archived for future update.
